### ISSUE TITLE
Substitute for Q2 Needed (Impossible to buy)

### ISSUE THREAD

**Issue by va3ngc** [John-Nagle/ttyloopdriver#9]
Is there a suitable substitute for Q2 (DN2625K4-G) as these seem to be backordered for at least a year at Digi-Key and Mouser and there are none available currently on eBay either?

**Comment by va3ngc** [comment]
Was able to find Q2 from UK via Newark.  Issue has been resolved.

**Comment by John-Nagle** [comment]
I'm glad you found one.

Q2 is for a two-component current regulator with significant power dissipation capability. It limits the output loop current to 60mA, even for a dead short. Unfortunately, depletion-mode FETs are somewhat exotic parts, because few people do current loops today.
